// GENERATED CODE -- DO NOT EDIT!

// package: google.devtools.containeranalysis.v1alpha1
// file: google/devtools/containeranalysis/v1alpha1/containeranalysis.proto

import * as google_devtools_containeranalysis_v1alpha1_containeranalysis_pb from "../../../../google/devtools/containeranalysis/v1alpha1/containeranalysis_pb";
import * as google_iam_v1_iam_policy_pb from "../../../../google/iam/v1/iam_policy_pb";
import * as google_iam_v1_policy_pb from "../../../../google/iam/v1/policy_pb";
import * as google_longrunning_operations_pb from "../../../../google/longrunning/operations_pb";
import * as google_protobuf_empty_pb from "google-protobuf/google/protobuf/empty_pb";
import * as grpc from "grpc";

interface IContainerAnalysisService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  getOccurrence: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetOccurrenceRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>;
  listOccurrences: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListOccurrencesRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListOccurrencesResponse>;
  deleteOccurrence: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.DeleteOccurrenceRequest, google_protobuf_empty_pb.Empty>;
  createOccurrence: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateOccurrenceRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>;
  updateOccurrence: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateOccurrenceRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>;
  getOccurrenceNote: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetOccurrenceNoteRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>;
  getNote: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetNoteRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>;
  listNotes: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNotesRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNotesResponse>;
  deleteNote: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.DeleteNoteRequest, google_protobuf_empty_pb.Empty>;
  createNote: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateNoteRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>;
  updateNote: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateNoteRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>;
  listNoteOccurrences: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNoteOccurrencesRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNoteOccurrencesResponse>;
  getVulnzOccurrencesSummary: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetVulnzOccurrencesSummaryRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetVulnzOccurrencesSummaryResponse>;
  setIamPolicy: grpc.MethodDefinition<google_iam_v1_iam_policy_pb.SetIamPolicyRequest, google_iam_v1_policy_pb.Policy>;
  getIamPolicy: grpc.MethodDefinition<google_iam_v1_iam_policy_pb.GetIamPolicyRequest, google_iam_v1_policy_pb.Policy>;
  testIamPermissions: grpc.MethodDefinition<google_iam_v1_iam_policy_pb.TestIamPermissionsRequest, google_iam_v1_iam_policy_pb.TestIamPermissionsResponse>;
  createOperation: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateOperationRequest, google_longrunning_operations_pb.Operation>;
  updateOperation: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateOperationRequest, google_longrunning_operations_pb.Operation>;
  getScanConfig: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetScanConfigRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ScanConfig>;
  listScanConfigs: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListScanConfigsRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListScanConfigsResponse>;
  updateScanConfig: grpc.MethodDefinition<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateScanConfigRequest, google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ScanConfig>;
}

export const ContainerAnalysisService: IContainerAnalysisService;

export class ContainerAnalysisClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  getOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetOccurrenceRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>): grpc.ClientUnaryCall;
  getOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetOccurrenceRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>): grpc.ClientUnaryCall;
  getOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetOccurrenceRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>): grpc.ClientUnaryCall;
  listOccurrences(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListOccurrencesRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListOccurrencesResponse>): grpc.ClientUnaryCall;
  listOccurrences(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListOccurrencesRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListOccurrencesResponse>): grpc.ClientUnaryCall;
  listOccurrences(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListOccurrencesRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListOccurrencesResponse>): grpc.ClientUnaryCall;
  deleteOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.DeleteOccurrenceRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.DeleteOccurrenceRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.DeleteOccurrenceRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateOccurrenceRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>): grpc.ClientUnaryCall;
  createOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateOccurrenceRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>): grpc.ClientUnaryCall;
  createOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateOccurrenceRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>): grpc.ClientUnaryCall;
  updateOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateOccurrenceRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>): grpc.ClientUnaryCall;
  updateOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateOccurrenceRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>): grpc.ClientUnaryCall;
  updateOccurrence(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateOccurrenceRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Occurrence>): grpc.ClientUnaryCall;
  getOccurrenceNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetOccurrenceNoteRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  getOccurrenceNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetOccurrenceNoteRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  getOccurrenceNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetOccurrenceNoteRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  getNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetNoteRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  getNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetNoteRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  getNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetNoteRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  listNotes(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNotesRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNotesResponse>): grpc.ClientUnaryCall;
  listNotes(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNotesRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNotesResponse>): grpc.ClientUnaryCall;
  listNotes(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNotesRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNotesResponse>): grpc.ClientUnaryCall;
  deleteNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.DeleteNoteRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.DeleteNoteRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.DeleteNoteRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateNoteRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  createNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateNoteRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  createNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateNoteRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  updateNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateNoteRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  updateNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateNoteRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  updateNote(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateNoteRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.Note>): grpc.ClientUnaryCall;
  listNoteOccurrences(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNoteOccurrencesRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNoteOccurrencesResponse>): grpc.ClientUnaryCall;
  listNoteOccurrences(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNoteOccurrencesRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNoteOccurrencesResponse>): grpc.ClientUnaryCall;
  listNoteOccurrences(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNoteOccurrencesRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListNoteOccurrencesResponse>): grpc.ClientUnaryCall;
  getVulnzOccurrencesSummary(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetVulnzOccurrencesSummaryRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetVulnzOccurrencesSummaryResponse>): grpc.ClientUnaryCall;
  getVulnzOccurrencesSummary(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetVulnzOccurrencesSummaryRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetVulnzOccurrencesSummaryResponse>): grpc.ClientUnaryCall;
  getVulnzOccurrencesSummary(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetVulnzOccurrencesSummaryRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetVulnzOccurrencesSummaryResponse>): grpc.ClientUnaryCall;
  setIamPolicy(argument: google_iam_v1_iam_policy_pb.SetIamPolicyRequest, callback: grpc.requestCallback<google_iam_v1_policy_pb.Policy>): grpc.ClientUnaryCall;
  setIamPolicy(argument: google_iam_v1_iam_policy_pb.SetIamPolicyRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_iam_v1_policy_pb.Policy>): grpc.ClientUnaryCall;
  setIamPolicy(argument: google_iam_v1_iam_policy_pb.SetIamPolicyRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_iam_v1_policy_pb.Policy>): grpc.ClientUnaryCall;
  getIamPolicy(argument: google_iam_v1_iam_policy_pb.GetIamPolicyRequest, callback: grpc.requestCallback<google_iam_v1_policy_pb.Policy>): grpc.ClientUnaryCall;
  getIamPolicy(argument: google_iam_v1_iam_policy_pb.GetIamPolicyRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_iam_v1_policy_pb.Policy>): grpc.ClientUnaryCall;
  getIamPolicy(argument: google_iam_v1_iam_policy_pb.GetIamPolicyRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_iam_v1_policy_pb.Policy>): grpc.ClientUnaryCall;
  testIamPermissions(argument: google_iam_v1_iam_policy_pb.TestIamPermissionsRequest, callback: grpc.requestCallback<google_iam_v1_iam_policy_pb.TestIamPermissionsResponse>): grpc.ClientUnaryCall;
  testIamPermissions(argument: google_iam_v1_iam_policy_pb.TestIamPermissionsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_iam_v1_iam_policy_pb.TestIamPermissionsResponse>): grpc.ClientUnaryCall;
  testIamPermissions(argument: google_iam_v1_iam_policy_pb.TestIamPermissionsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_iam_v1_iam_policy_pb.TestIamPermissionsResponse>): grpc.ClientUnaryCall;
  createOperation(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateOperationRequest, callback: grpc.requestCallback<google_longrunning_operations_pb.Operation>): grpc.ClientUnaryCall;
  createOperation(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateOperationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_longrunning_operations_pb.Operation>): grpc.ClientUnaryCall;
  createOperation(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.CreateOperationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_longrunning_operations_pb.Operation>): grpc.ClientUnaryCall;
  updateOperation(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateOperationRequest, callback: grpc.requestCallback<google_longrunning_operations_pb.Operation>): grpc.ClientUnaryCall;
  updateOperation(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateOperationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_longrunning_operations_pb.Operation>): grpc.ClientUnaryCall;
  updateOperation(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateOperationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_longrunning_operations_pb.Operation>): grpc.ClientUnaryCall;
  getScanConfig(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetScanConfigRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ScanConfig>): grpc.ClientUnaryCall;
  getScanConfig(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetScanConfigRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ScanConfig>): grpc.ClientUnaryCall;
  getScanConfig(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.GetScanConfigRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ScanConfig>): grpc.ClientUnaryCall;
  listScanConfigs(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListScanConfigsRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListScanConfigsResponse>): grpc.ClientUnaryCall;
  listScanConfigs(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListScanConfigsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListScanConfigsResponse>): grpc.ClientUnaryCall;
  listScanConfigs(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListScanConfigsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ListScanConfigsResponse>): grpc.ClientUnaryCall;
  updateScanConfig(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateScanConfigRequest, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ScanConfig>): grpc.ClientUnaryCall;
  updateScanConfig(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateScanConfigRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ScanConfig>): grpc.ClientUnaryCall;
  updateScanConfig(argument: google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.UpdateScanConfigRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_containeranalysis_v1alpha1_containeranalysis_pb.ScanConfig>): grpc.ClientUnaryCall;
}
