// GENERATED CODE -- DO NOT EDIT!

// package: google.devtools.resultstore.v2
// file: google/devtools/resultstore/v2/resultstore_upload.proto

import * as google_devtools_resultstore_v2_resultstore_upload_pb from "../../../../google/devtools/resultstore/v2/resultstore_upload_pb";
import * as google_devtools_resultstore_v2_action_pb from "../../../../google/devtools/resultstore/v2/action_pb";
import * as google_devtools_resultstore_v2_configuration_pb from "../../../../google/devtools/resultstore/v2/configuration_pb";
import * as google_devtools_resultstore_v2_configured_target_pb from "../../../../google/devtools/resultstore/v2/configured_target_pb";
import * as google_devtools_resultstore_v2_file_set_pb from "../../../../google/devtools/resultstore/v2/file_set_pb";
import * as google_devtools_resultstore_v2_invocation_pb from "../../../../google/devtools/resultstore/v2/invocation_pb";
import * as google_devtools_resultstore_v2_target_pb from "../../../../google/devtools/resultstore/v2/target_pb";
import * as google_devtools_resultstore_v2_upload_metadata_pb from "../../../../google/devtools/resultstore/v2/upload_metadata_pb";
import * as google_protobuf_empty_pb from "google-protobuf/google/protobuf/empty_pb";
import * as grpc from "grpc";

interface IResultStoreUploadService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  createInvocation: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.CreateInvocationRequest, google_devtools_resultstore_v2_invocation_pb.Invocation>;
  updateInvocation: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.UpdateInvocationRequest, google_devtools_resultstore_v2_invocation_pb.Invocation>;
  mergeInvocation: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.MergeInvocationRequest, google_devtools_resultstore_v2_invocation_pb.Invocation>;
  touchInvocation: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.TouchInvocationRequest, google_devtools_resultstore_v2_resultstore_upload_pb.TouchInvocationResponse>;
  finalizeInvocation: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeInvocationRequest, google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeInvocationResponse>;
  deleteInvocation: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.DeleteInvocationRequest, google_protobuf_empty_pb.Empty>;
  createTarget: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.CreateTargetRequest, google_devtools_resultstore_v2_target_pb.Target>;
  updateTarget: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.UpdateTargetRequest, google_devtools_resultstore_v2_target_pb.Target>;
  mergeTarget: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.MergeTargetRequest, google_devtools_resultstore_v2_target_pb.Target>;
  finalizeTarget: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeTargetRequest, google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeTargetResponse>;
  createConfiguredTarget: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.CreateConfiguredTargetRequest, google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>;
  updateConfiguredTarget: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.UpdateConfiguredTargetRequest, google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>;
  mergeConfiguredTarget: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.MergeConfiguredTargetRequest, google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>;
  finalizeConfiguredTarget: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeConfiguredTargetRequest, google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeConfiguredTargetResponse>;
  createAction: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.CreateActionRequest, google_devtools_resultstore_v2_action_pb.Action>;
  updateAction: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.UpdateActionRequest, google_devtools_resultstore_v2_action_pb.Action>;
  mergeAction: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.MergeActionRequest, google_devtools_resultstore_v2_action_pb.Action>;
  createConfiguration: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.CreateConfigurationRequest, google_devtools_resultstore_v2_configuration_pb.Configuration>;
  updateConfiguration: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.UpdateConfigurationRequest, google_devtools_resultstore_v2_configuration_pb.Configuration>;
  createFileSet: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.CreateFileSetRequest, google_devtools_resultstore_v2_file_set_pb.FileSet>;
  updateFileSet: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.UpdateFileSetRequest, google_devtools_resultstore_v2_file_set_pb.FileSet>;
  mergeFileSet: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.MergeFileSetRequest, google_devtools_resultstore_v2_file_set_pb.FileSet>;
  uploadBatch: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.UploadBatchRequest, google_devtools_resultstore_v2_resultstore_upload_pb.UploadBatchResponse>;
  getInvocationUploadMetadata: grpc.MethodDefinition<google_devtools_resultstore_v2_resultstore_upload_pb.GetInvocationUploadMetadataRequest, google_devtools_resultstore_v2_upload_metadata_pb.UploadMetadata>;
}

export const ResultStoreUploadService: IResultStoreUploadService;

export class ResultStoreUploadClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  createInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateInvocationRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_invocation_pb.Invocation>): grpc.ClientUnaryCall;
  createInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateInvocationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_invocation_pb.Invocation>): grpc.ClientUnaryCall;
  createInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateInvocationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_invocation_pb.Invocation>): grpc.ClientUnaryCall;
  updateInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateInvocationRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_invocation_pb.Invocation>): grpc.ClientUnaryCall;
  updateInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateInvocationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_invocation_pb.Invocation>): grpc.ClientUnaryCall;
  updateInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateInvocationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_invocation_pb.Invocation>): grpc.ClientUnaryCall;
  mergeInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeInvocationRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_invocation_pb.Invocation>): grpc.ClientUnaryCall;
  mergeInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeInvocationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_invocation_pb.Invocation>): grpc.ClientUnaryCall;
  mergeInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeInvocationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_invocation_pb.Invocation>): grpc.ClientUnaryCall;
  touchInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.TouchInvocationRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.TouchInvocationResponse>): grpc.ClientUnaryCall;
  touchInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.TouchInvocationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.TouchInvocationResponse>): grpc.ClientUnaryCall;
  touchInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.TouchInvocationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.TouchInvocationResponse>): grpc.ClientUnaryCall;
  finalizeInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeInvocationRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeInvocationResponse>): grpc.ClientUnaryCall;
  finalizeInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeInvocationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeInvocationResponse>): grpc.ClientUnaryCall;
  finalizeInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeInvocationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeInvocationResponse>): grpc.ClientUnaryCall;
  deleteInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.DeleteInvocationRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.DeleteInvocationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteInvocation(argument: google_devtools_resultstore_v2_resultstore_upload_pb.DeleteInvocationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  createTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateTargetRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_target_pb.Target>): grpc.ClientUnaryCall;
  createTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateTargetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_target_pb.Target>): grpc.ClientUnaryCall;
  createTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateTargetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_target_pb.Target>): grpc.ClientUnaryCall;
  updateTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateTargetRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_target_pb.Target>): grpc.ClientUnaryCall;
  updateTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateTargetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_target_pb.Target>): grpc.ClientUnaryCall;
  updateTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateTargetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_target_pb.Target>): grpc.ClientUnaryCall;
  mergeTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeTargetRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_target_pb.Target>): grpc.ClientUnaryCall;
  mergeTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeTargetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_target_pb.Target>): grpc.ClientUnaryCall;
  mergeTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeTargetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_target_pb.Target>): grpc.ClientUnaryCall;
  finalizeTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeTargetRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeTargetResponse>): grpc.ClientUnaryCall;
  finalizeTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeTargetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeTargetResponse>): grpc.ClientUnaryCall;
  finalizeTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeTargetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeTargetResponse>): grpc.ClientUnaryCall;
  createConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateConfiguredTargetRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>): grpc.ClientUnaryCall;
  createConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateConfiguredTargetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>): grpc.ClientUnaryCall;
  createConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateConfiguredTargetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>): grpc.ClientUnaryCall;
  updateConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateConfiguredTargetRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>): grpc.ClientUnaryCall;
  updateConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateConfiguredTargetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>): grpc.ClientUnaryCall;
  updateConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateConfiguredTargetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>): grpc.ClientUnaryCall;
  mergeConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeConfiguredTargetRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>): grpc.ClientUnaryCall;
  mergeConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeConfiguredTargetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>): grpc.ClientUnaryCall;
  mergeConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeConfiguredTargetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_configured_target_pb.ConfiguredTarget>): grpc.ClientUnaryCall;
  finalizeConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeConfiguredTargetRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeConfiguredTargetResponse>): grpc.ClientUnaryCall;
  finalizeConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeConfiguredTargetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeConfiguredTargetResponse>): grpc.ClientUnaryCall;
  finalizeConfiguredTarget(argument: google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeConfiguredTargetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.FinalizeConfiguredTargetResponse>): grpc.ClientUnaryCall;
  createAction(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateActionRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_action_pb.Action>): grpc.ClientUnaryCall;
  createAction(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateActionRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_action_pb.Action>): grpc.ClientUnaryCall;
  createAction(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateActionRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_action_pb.Action>): grpc.ClientUnaryCall;
  updateAction(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateActionRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_action_pb.Action>): grpc.ClientUnaryCall;
  updateAction(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateActionRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_action_pb.Action>): grpc.ClientUnaryCall;
  updateAction(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateActionRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_action_pb.Action>): grpc.ClientUnaryCall;
  mergeAction(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeActionRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_action_pb.Action>): grpc.ClientUnaryCall;
  mergeAction(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeActionRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_action_pb.Action>): grpc.ClientUnaryCall;
  mergeAction(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeActionRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_action_pb.Action>): grpc.ClientUnaryCall;
  createConfiguration(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateConfigurationRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_configuration_pb.Configuration>): grpc.ClientUnaryCall;
  createConfiguration(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateConfigurationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_configuration_pb.Configuration>): grpc.ClientUnaryCall;
  createConfiguration(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateConfigurationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_configuration_pb.Configuration>): grpc.ClientUnaryCall;
  updateConfiguration(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateConfigurationRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_configuration_pb.Configuration>): grpc.ClientUnaryCall;
  updateConfiguration(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateConfigurationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_configuration_pb.Configuration>): grpc.ClientUnaryCall;
  updateConfiguration(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateConfigurationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_configuration_pb.Configuration>): grpc.ClientUnaryCall;
  createFileSet(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateFileSetRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_file_set_pb.FileSet>): grpc.ClientUnaryCall;
  createFileSet(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateFileSetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_file_set_pb.FileSet>): grpc.ClientUnaryCall;
  createFileSet(argument: google_devtools_resultstore_v2_resultstore_upload_pb.CreateFileSetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_file_set_pb.FileSet>): grpc.ClientUnaryCall;
  updateFileSet(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateFileSetRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_file_set_pb.FileSet>): grpc.ClientUnaryCall;
  updateFileSet(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateFileSetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_file_set_pb.FileSet>): grpc.ClientUnaryCall;
  updateFileSet(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UpdateFileSetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_file_set_pb.FileSet>): grpc.ClientUnaryCall;
  mergeFileSet(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeFileSetRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_file_set_pb.FileSet>): grpc.ClientUnaryCall;
  mergeFileSet(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeFileSetRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_file_set_pb.FileSet>): grpc.ClientUnaryCall;
  mergeFileSet(argument: google_devtools_resultstore_v2_resultstore_upload_pb.MergeFileSetRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_file_set_pb.FileSet>): grpc.ClientUnaryCall;
  uploadBatch(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UploadBatchRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.UploadBatchResponse>): grpc.ClientUnaryCall;
  uploadBatch(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UploadBatchRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.UploadBatchResponse>): grpc.ClientUnaryCall;
  uploadBatch(argument: google_devtools_resultstore_v2_resultstore_upload_pb.UploadBatchRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_resultstore_upload_pb.UploadBatchResponse>): grpc.ClientUnaryCall;
  getInvocationUploadMetadata(argument: google_devtools_resultstore_v2_resultstore_upload_pb.GetInvocationUploadMetadataRequest, callback: grpc.requestCallback<google_devtools_resultstore_v2_upload_metadata_pb.UploadMetadata>): grpc.ClientUnaryCall;
  getInvocationUploadMetadata(argument: google_devtools_resultstore_v2_resultstore_upload_pb.GetInvocationUploadMetadataRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_upload_metadata_pb.UploadMetadata>): grpc.ClientUnaryCall;
  getInvocationUploadMetadata(argument: google_devtools_resultstore_v2_resultstore_upload_pb.GetInvocationUploadMetadataRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_devtools_resultstore_v2_upload_metadata_pb.UploadMetadata>): grpc.ClientUnaryCall;
}
