// GENERATED CODE -- DO NOT EDIT!

// package: google.cloud.bigquery.datatransfer.v1
// file: google/cloud/bigquery/datatransfer/v1/datatransfer.proto

import * as google_cloud_bigquery_datatransfer_v1_datatransfer_pb from "../../../../../google/cloud/bigquery/datatransfer/v1/datatransfer_pb";
import * as google_cloud_bigquery_datatransfer_v1_transfer_pb from "../../../../../google/cloud/bigquery/datatransfer/v1/transfer_pb";
import * as google_protobuf_empty_pb from "google-protobuf/google/protobuf/empty_pb";
import * as grpc from "grpc";

interface IDataTransferServiceService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  getDataSource: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetDataSourceRequest, google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DataSource>;
  listDataSources: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListDataSourcesRequest, google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListDataSourcesResponse>;
  createTransferConfig: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CreateTransferConfigRequest, google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>;
  updateTransferConfig: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.UpdateTransferConfigRequest, google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>;
  deleteTransferConfig: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DeleteTransferConfigRequest, google_protobuf_empty_pb.Empty>;
  getTransferConfig: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetTransferConfigRequest, google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>;
  listTransferConfigs: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferConfigsRequest, google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferConfigsResponse>;
  scheduleTransferRuns: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ScheduleTransferRunsRequest, google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ScheduleTransferRunsResponse>;
  startManualTransferRuns: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.StartManualTransferRunsRequest, google_cloud_bigquery_datatransfer_v1_datatransfer_pb.StartManualTransferRunsResponse>;
  getTransferRun: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetTransferRunRequest, google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferRun>;
  deleteTransferRun: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DeleteTransferRunRequest, google_protobuf_empty_pb.Empty>;
  listTransferRuns: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferRunsRequest, google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferRunsResponse>;
  listTransferLogs: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferLogsRequest, google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferLogsResponse>;
  checkValidCreds: grpc.MethodDefinition<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CheckValidCredsRequest, google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CheckValidCredsResponse>;
}

export const DataTransferServiceService: IDataTransferServiceService;

export class DataTransferServiceClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  getDataSource(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetDataSourceRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DataSource>): grpc.ClientUnaryCall;
  getDataSource(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetDataSourceRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DataSource>): grpc.ClientUnaryCall;
  getDataSource(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetDataSourceRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DataSource>): grpc.ClientUnaryCall;
  listDataSources(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListDataSourcesRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListDataSourcesResponse>): grpc.ClientUnaryCall;
  listDataSources(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListDataSourcesRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListDataSourcesResponse>): grpc.ClientUnaryCall;
  listDataSources(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListDataSourcesRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListDataSourcesResponse>): grpc.ClientUnaryCall;
  createTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CreateTransferConfigRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>): grpc.ClientUnaryCall;
  createTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CreateTransferConfigRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>): grpc.ClientUnaryCall;
  createTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CreateTransferConfigRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>): grpc.ClientUnaryCall;
  updateTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.UpdateTransferConfigRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>): grpc.ClientUnaryCall;
  updateTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.UpdateTransferConfigRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>): grpc.ClientUnaryCall;
  updateTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.UpdateTransferConfigRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>): grpc.ClientUnaryCall;
  deleteTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DeleteTransferConfigRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DeleteTransferConfigRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DeleteTransferConfigRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  getTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetTransferConfigRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>): grpc.ClientUnaryCall;
  getTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetTransferConfigRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>): grpc.ClientUnaryCall;
  getTransferConfig(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetTransferConfigRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferConfig>): grpc.ClientUnaryCall;
  listTransferConfigs(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferConfigsRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferConfigsResponse>): grpc.ClientUnaryCall;
  listTransferConfigs(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferConfigsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferConfigsResponse>): grpc.ClientUnaryCall;
  listTransferConfigs(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferConfigsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferConfigsResponse>): grpc.ClientUnaryCall;
  scheduleTransferRuns(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ScheduleTransferRunsRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ScheduleTransferRunsResponse>): grpc.ClientUnaryCall;
  scheduleTransferRuns(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ScheduleTransferRunsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ScheduleTransferRunsResponse>): grpc.ClientUnaryCall;
  scheduleTransferRuns(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ScheduleTransferRunsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ScheduleTransferRunsResponse>): grpc.ClientUnaryCall;
  startManualTransferRuns(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.StartManualTransferRunsRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.StartManualTransferRunsResponse>): grpc.ClientUnaryCall;
  startManualTransferRuns(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.StartManualTransferRunsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.StartManualTransferRunsResponse>): grpc.ClientUnaryCall;
  startManualTransferRuns(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.StartManualTransferRunsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.StartManualTransferRunsResponse>): grpc.ClientUnaryCall;
  getTransferRun(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetTransferRunRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferRun>): grpc.ClientUnaryCall;
  getTransferRun(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetTransferRunRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferRun>): grpc.ClientUnaryCall;
  getTransferRun(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.GetTransferRunRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_transfer_pb.TransferRun>): grpc.ClientUnaryCall;
  deleteTransferRun(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DeleteTransferRunRequest, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteTransferRun(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DeleteTransferRunRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  deleteTransferRun(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.DeleteTransferRunRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_protobuf_empty_pb.Empty>): grpc.ClientUnaryCall;
  listTransferRuns(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferRunsRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferRunsResponse>): grpc.ClientUnaryCall;
  listTransferRuns(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferRunsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferRunsResponse>): grpc.ClientUnaryCall;
  listTransferRuns(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferRunsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferRunsResponse>): grpc.ClientUnaryCall;
  listTransferLogs(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferLogsRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferLogsResponse>): grpc.ClientUnaryCall;
  listTransferLogs(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferLogsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferLogsResponse>): grpc.ClientUnaryCall;
  listTransferLogs(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferLogsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.ListTransferLogsResponse>): grpc.ClientUnaryCall;
  checkValidCreds(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CheckValidCredsRequest, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CheckValidCredsResponse>): grpc.ClientUnaryCall;
  checkValidCreds(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CheckValidCredsRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CheckValidCredsResponse>): grpc.ClientUnaryCall;
  checkValidCreds(argument: google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CheckValidCredsRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<google_cloud_bigquery_datatransfer_v1_datatransfer_pb.CheckValidCredsResponse>): grpc.ClientUnaryCall;
}
